[package]
name = "host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "10.0.1"
wasmtime-wasi = "10.0.1"
anyhow = "1.0.71"
rand = "0.8.5"